### ISSUE TITLE
epub version

### ISSUE THREAD

**Issue by saihttam** [christophM/interpretable-ml-book#10]
An ePub version could be easily supported by adding the option to the _output.yml, e.g.:
```
bookdown::epub_book:
  dev: svglite
```
An example can be seen here: https://github.com/rstudio/bookdown/blob/master/inst/examples/_output.yml
Rendering seems to work fine with standard settings.

**Comment by MHonegger** [comment]
@christophM 
First of all I would like to thank you for the amazing book you are putting together. In my master thesis I am researching and writing about closely related topics. Your book hast been a great help for that.

I would like to ask you, if you could not make your book 'downloadable' as a pdf or epub as suggested above, as that would allow everyone to print it. Unfortunately it is very hard to read and annotate it in its current form, which is a shame as it is a great book with which I'd like to work more!

Thank you very much in advance!
Best, 
Milo

**Comment by christophM** [comment]
I am planning to publish the book on Leanpub in the coming weeks (pdf + epub + mobi). Stay tuned!

**Comment by christophM** [comment]
https://leanpub.com/interpretable-machine-learning
