### ISSUE TITLE
Make the "next page >" symbol more obvious on the Preface page

### ISSUE THREAD

**Issue by hpssjellis** [christophM/interpretable-ml-book#102]
On my cell phone the next page symbol ">" is a light grey and very small. Even though I had my cell read "Desktop site" no menu or side bar was visible. I almost ignored your book since I could only see the preface.

![book02](https://user-images.githubusercontent.com/5605614/53295202-1d2e0000-37ab-11e9-8d8b-7e24be240435.png)

Suggest making a regular link on the preface page to the next page.

**Comment by christophM** [comment]
Thanks for letting me know! I am using the R bookdown package, so it would be a bit more work to change the CSS.
