### ISSUE TITLE
5.1.1 Examples - Seasons PDP

### ISSUE THREAD

**Issue by lcrmorin** [christophM/interpretable-ml-book#108]
I understand the data set include 2 years of bike renting, starting january. I feel like the order of spring, summer, autumn, winter in PDP may come from the correlation of seasons to time passing by, which is one of the main predictive variable. The label of the figure seems to conclude that season has no effect, while the conclusion should be about checking the correlation of season to "days_since_2011".

**Comment by christophM** [comment]
Thanks for the remark. Since the PDP is analyzing the model, the conclusion is of course for the model behavior, not the “true world“. I changed the figure label to make it more clear.
