### ISSUE TITLE
5.5 Feature Importance

### ISSUE THREAD

**Issue by lcrmorin** [christophM/interpretable-ml-book#111]
Feature importance is defined here using permutation of variables. I am not sure this is a standard appelation. See for example The Elements of Statistical Learning (10.13 Interpretation p367), where feature importance is defined relative to a subset of variables. Maybe the name of the concept can be changed.

**Comment by christophM** [comment]
You are right, there are other possibilities for computing feature importance. I renamed the chapter to be more accurate.
