### ISSUE TITLE
5.5 Feature Importance

### ISSUE THREAD

**Issue by lcrmorin** [christophM/interpretable-ml-book#112]
I have a problem implementing this method. I have variables that take very high values and other that take very small values. My model mostly have calibrated small parameters for variable that take very high value and big parameters for variables that take small values. When using the procedure sometime a variable with big value will be swapped with a very small one, throwing of the estimated importance (big parameter * big value). I feel like it should be precised that this method rely on normalising the data beforehand. More generally, I am not sure which other methods would require such normalisation or not.

**Comment by christophM** [comment]
From what you write, it seems like the instability is more a property of the model and not of the permutation feature importance. At least to the best of my knowledge permutation feature importance does not require normalization.
