### ISSUE TITLE
MUSE (Lakkaraju et al 2019)

### ISSUE THREAD

**Issue by ellliottt** [christophM/interpretable-ml-book#119]
Consider adding a section outlining the approach in 

Lakkaraju, Kamar, Caruana, and Leskovec (2019)
Faithful and customizable explanations of black box models
https://cs.stanford.edu/people/jure/pubs/explanations-aies19.pdf

**Comment by christophM** [comment]
Is there some open source implementation of the method or the code of the paper available somewhere?

**Comment by christophM** [comment]
Closing because of lack of implementation
