### ISSUE TITLE
Model-agnostic Permutation Feature Importance

### ISSUE THREAD

**Issue by beeva-josealberto** [christophM/interpretable-ml-book#12]
Hi Christoph, and thank you for the great book!

In the **Permutation Feature Importance** section you say:

> I haven’t found any paper that generalises permutation feature importance, so that it can be applied model-agnostic. Please drop me a mail if you know about model-agnostic feature importance.

But you propose a model-agnostic version of the algorithm in the same section. Did you forget to remove that couple of sentences? Or am I missing something?

**Comment by christophM** [comment]
Hi 
While I did not find any paper about model-agnostic permutation feature importance, it is straightforward to generalize the permutation feature importance from RandomForests. This is what I have written down. 
But it would be good to have a paper that actually formulates model-agnostic feature importance once and tests it extensively.
