### ISSUE TITLE
Model Specific Methods - xgboost

### ISSUE THREAD

**Issue by lcrmorin** [christophM/interpretable-ml-book#123]
I see there is now a model-specific methods section, starting with Neural Networks. You might be  interested in some advances in xgboost - and more generally trees - explainability. Here is a [medium post](https://medium.com/applied-data-science/new-r-package-the-xgboost-explainer-51dd7d1aa211)  that explain the method (I am not sure it is new or even meaningfull for small trees). However I have found the publication of the R xgboostExplainer package of interest, and quite usefull to use given the general performance of xgboost models. I am particularly fond of the waterfall diagrams to translate the variable impacts in log-odds.

**Comment by christophM** [comment]
Thanks for the suggestion and the link! Indeed I am planning to write something for random forests and boosted tree ensembles such as xgboost.

**Comment by christophM** [comment]
Thanks for that suggestion (I know it was 1.5 years ago =)). For a long time I was not sure about the scope of the book. But after this long time I decided to only include model-agnostic techniques, simple interpretable models and some deep learning specific stuff.
