### ISSUE TITLE
Determine the validity of feature importance for a regression

### ISSUE THREAD

**Issue by Hadsga** [christophM/interpretable-ml-book#128]
My goal is to determine the "Feature Importance" for a regression task (i.e. I want to know which feature influences the target variable the most). 

I read your (great) book, in which you explain different methods such as the pros and cons of each method. However, I am still not sure how to choose the most accurate method for a given data set. For example, in market research, it´s quite important to know exactly which features drive aspects like customer loyalty. 

Let´s assume I use a multiple regression.

There are different methods to determine the feature importance: Model dependent measures like (standardized) Betacoefficients, Shapley Value Regression and model-independent measures like Permutation Importance.

All methods are made for specific situations (i.e. Shapely Value Regression is made for situations in which the features are highly correlated, where permutation importance takes interaction effects into account). However, these assumptions are a result of theoretical considerations evaluated on simulated data sets. However, the validity (the difference between the "true"  and the measured feature importance) is dependent on the structure of the actual data set.

So my question ist, if there a way In R to determine the measured difference between the measured and the "true" values of the feature importance?

In your book, you use Python and R to calculate different measures.  I usually use R, so my example is based on R. 

An idea is to use cross-validation. With cross-validation, I can measure the difference between the predicted and the actual values on a given data set.  

As an example, I use the Hitters data set.

```
library(ISLR)
library(caret)


fit = train(Salary~., data = Hitters, method = "lm", trControl = trainControl(method = "repeatedcv", repeats = 3), na.action = na.omit, savePredictions = 'final' )
```

I can take a look at the tuning results and the difference between true and predicted values. Here I have an RMSE of ~ 334.

```
  intercept     RMSE Rsquared      MAE   RMSESD RsquaredSD    MAESD
1      TRUE 333.9667 0.468769 239.7604 75.13388  0.1987425 40.58342
```

But what´s about the Beta coefficients. I can look at them but can't figure out how they differ from the actual betas on the test set.

```
coef(fit$finalModel)
 (Intercept)        AtBat         Hits        HmRun         Runs          RBI        Walks        Years       CAtBat        CHits       CHmRun 
 163.1035878   -1.9798729    7.5007675    4.3308829   -2.3762100   -1.0449620    6.2312863   -3.4890543   -0.1713405    0.1339910   -0.1728611 
       CRuns         CRBI       CWalks      LeagueN    DivisionW      PutOuts      Assists       Errors   NewLeagueN 
   1.4543049    0.8077088   -0.8115709   62.5994230 -116.8492456    0.2818925    0.3710692 
```
Is there a way in R to get this information (also for other measures like the Permutation Importance or Shapely Value Regression)?

**Comment by christophM** [comment]
There is no “true“ feature importance, but only different definitions. For regression you an also use standardized regression coefficients to compare importances.
Maybe your question can be answered if you put it on stackoverflow or stackexchange
