### ISSUE TITLE
Mention Software for Counterfactual Explanations

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#131]
Add Alibi:
https://docs.seldon.io/projects/alibi/en/latest/methods/CF.html

Also do some more research

**Comment by jklaise** [comment]
Are you open to a PR for this? A few sentences mentioning our Alibi implementation and maybe a link to our new paper (https://arxiv.org/abs/1907.02584) for an improvement on the basic algorithm by Wachter et al.

**Comment by christophM** [comment]
Yes, that sounds good.
