### ISSUE TITLE
Fix plots

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#134]
The anchors plots legends are cut off.
![unnamed-chunk-28-1](https://user-images.githubusercontent.com/1632100/63175108-99f7b380-c043-11e9-92c1-81189edd6ff3.png)
![unnamed-chunk-27-1](https://user-images.githubusercontent.com/1632100/63175112-9b28e080-c043-11e9-951f-0845533a8b4c.png)
![unnamed-chunk-25-1](https://user-images.githubusercontent.com/1632100/63175114-9c5a0d80-c043-11e9-844c-43c38760fa35.png)

**Comment by TobiasGoerke** [comment]
Plots are fixed!
They look like this in the rendered book:


![grafik](https://user-images.githubusercontent.com/13769461/63353742-827e3a80-c363-11e9-81ee-30495afcceda.png)
![grafik](https://user-images.githubusercontent.com/13769461/63353753-8611c180-c363-11e9-8507-3b5d803b53e9.png)
![grafik](https://user-images.githubusercontent.com/13769461/63353756-88741b80-c363-11e9-907c-99e4ed1e3dfd.png)
![grafik](https://user-images.githubusercontent.com/13769461/63353762-8ad67580-c363-11e9-8396-5dc61cf4d940.png)
