### ISSUE TITLE
Contribute with step by step explanation (with python code) of how LIME for images works

### ISSUE THREAD

**Issue by arteagac** [christophM/interpretable-ml-book#137]
Dear Christoph,
I have a python notebook that explains step by step how LIME for images works. You can see it in the following link:
https://arteagac.github.io/blog.html

I wanted to ask you if you consider a good idea to add something like this in your book. I am not sure if the use of python is a limitation given that I can see that your book uses R markdown.

**Comment by arteagac** [comment]
Right now the notebook does not have detailed textual explanations but of course I could add them later to make the explained steps more clear.

**Comment by christophM** [comment]
Hi, thanks for asking. 
What do you mean by adding? A link to your notebook, or are you interested in extending the chapter?

**Comment by arteagac** [comment]
I'd be more than glad to extend the chapter if you consider that it is the best way to include the material in the book. Or if you consider that a link to the notebook is enough, that is also fine by me. An updated version of the notebook can be found in the following link:
https://nbviewer.jupyter.org/url/arteagac.github.io/blog/lime_image.ipynb

Please let me know if you have any comments or feedback about the content of the notebook.

**Comment by christophM** [comment]
Since the other chapters don't link to code (only to libraries that implement the methods) it's out of scope to link to code examples. But thanks for the suggestion!
