### ISSUE TITLE
Link function for Logistic Regression

### ISSUE THREAD

**Issue by ta94** [christophM/interpretable-ml-book#139]
In the page [https://christophm.github.io/interpretable-ml-book/extend-lm.html](url)

> The logistic regression model is also a GLM that assumes a Bernoulli distribution and uses the logistic function as the link function. 

I think the link function of Logistic Regression it Logit Function [https://en.wikipedia.org/wiki/Logit](url) ?

**Comment by christophM** [comment]
Thanks!
