### ISSUE TITLE
Stratification Approach to Partial Dependence for Codependent Variables

### ISSUE THREAD

**Issue by talegari** [christophM/interpretable-ml-book#145]
Is 'A Stratification Approach to Partial Dependence for Codependent Variables' (https://arxiv.org/abs/1907.06698) a worthy mention alongside PDP, ICE? Here are an implementation: https://github.com/parrt/stratx

related: https://github.com/christophM/interpretable-ml-book/issues/50

**Comment by christophM** [comment]
This was a bit confusing to me at first, but it seems like this method does not analyze a machine learning model. StratPD directly analyses the data.
So, at least for now, this is out of scope for this book.
