### ISSUE TITLE
Write a chapter about your favorite deep learning interpretability method

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#15]
There are many interpretability methods for deep neural networks. 
The field is very young and most methods are  quite new and under development. It's hard for a single person to keep track. This issue serves as a placeholder for interpretability methods specific for deep learning. 

Leave a comment if you are interested in adding a chapter. Any method that helps interpreting neural networks is interesting. A good starting point is to take a paper or some code library and explain it in simpler words, possibly with an example. 

Some possible starting points: 

Software: 
- https://medium.com/merantix/picasso-a-free-open-source-visualizer-for-cnns-d8ed3a35cfc5
- https://github.com/yosinski/deep-visualization-toolbox
- https://www.oreilly.com/ideas/interpretability-via-attentional-and-memory-based-interfaces-using-tensorflow
- https://github.com/taolei87/rcnn

Scientific Paper: 
- [Right for the Right Reasons: Training Differentiable Models by Constraining their Explanations](https://arxiv.org/pdf/1703.03717v1.pdf)
- [Rationalizing neural predictions](https://arxiv.org/abs/1606.04155)
- [Generating Visual Explanations](https://arxiv.org/abs/1603.08507)
- [Rationalization: A Neural Machine Translation Approach to Generating Natural Language Explanations](https://arxiv.org/abs/1702.07826)
- [Methods for interpreting and understanding deep neural networks](https://www.sciencedirect.com/science/article/pii/S1051200417302385)

Leave a comment if you are interested in writing a chapter!

**Comment by abi-aryan** [comment]
I will get to it.

**Comment by akalra** [comment]
Happy to help, I've been studying interpretability of CNNs for one project, and (very superficially) random forests for another project. Have used some of the tools above.

Will try to get to this in Dec.

**Comment by christophM** [comment]
I am kind of wrapping up the first version of the book at the moment. Also from the scope of the book I am not sure any more if I want to open up the big box of methods for neural networks at the moment. 
@akalra  I thinks it's best to discuss it in a call. Just send a mail to christoph.molnar.ai @ gmail.com
