### ISSUE TITLE
Permutation importance now in scikit learn v0.22

### ISSUE THREAD

**Issue by jamesmyatt** [christophM/interpretable-ml-book#153]
Scikit-learn has added permutation importance in the core library. https://scikit-learn.org/stable/whats_new/v0.22.html#sklearn-inspection

**Comment by huanfachen** [comment]
Adding to this note, there is another package called `rfpimp` that provides permutation feature importance for general sklearn models: https://pypi.org/project/rfpimp/

In my experiments, this package is more computationally efficient than permutation importance in sklearn.
