### ISSUE TITLE
Problem with adjusted R squared

### ISSUE THREAD

**Issue by huanfachen** [christophM/interpretable-ml-book#154]

**Comment by huanfachen** [comment]
In Section 4.1.1, the adjusted R squared is defined as: 
![equation](http://latex.codecogs.com/gif.latex?\bar{R}^2=R^2-(1-R^2)\frac{p}{n-p-1})

This is different from the definition on wikipedia (https://en.wikipedia.org/wiki/Coefficient_of_determination#Adjusted_R2), and not accurate.

Consider this new formula:
![equation](http://latex.codecogs.com/gif.latex?\bar{R}^2=R^2-(1-R^2)\frac{n-1}{n-p-1})

**Comment by christophM** [comment]
Good catch, thanks a lot!
