### ISSUE TITLE
Little fix in ALE

### ISSUE THREAD

**Issue by fbetteo** [christophM/interpretable-ml-book#157]
In 5.3.3 the interpretation of ALE says:
_"The value of the ALE can be interpreted as the main effect of the feature at a certain value compared to the average prediction of the data. For example, an ALE estimate of -2 at xj=3 means that when the j-th feature has value 3, then the prediction is lower by 2 compared to the average prediction.."_

Shouldn't it be "compared to the average **change** in prediction" ?

Also I think it is not completely clear why it is desirable to accumulate or why it is done. Any further clarification I think would be nice.

Tremendous work and great read! Keep it going!

**Comment by xiaochi-liu** [comment]
Hi there.  I also have a little question about Accumulated Local effects (ALE) in 5.3.3:

![image](https://user-images.githubusercontent.com/48895627/77845466-eb336c80-71fa-11ea-8f32-0bec63441251.png)

I was wondering, how the effect was centered? What does "n" stand for? the number of instances in a specific interval? in an accumulated interval? or across all intervals in the feature j?

In other words:

>  ALE plots are centered at zero. This makes their interpretation nice, because the value at each point of the ALE curve is the difference to the mean prediction.

What is the mean prediction? Could you please explain it more detailed?

Thank you so much. I like this book.

**Comment by christophM** [comment]
The interpretation of ALE is not so straightforward, so both my current version is not perfect, but also it's not "compared to the average change in prediction".
