### ISSUE TITLE
Extremely Minor Typo in Section 5.9.1

### ISSUE THREAD

**Issue by ijoseph** [christophM/interpretable-ml-book#159]
> In our apartment example, the feature values `park-nearby`, `cat-banned`, `area-50` and `floor-2nd`

should be 

> In our apartment example, the feature values `park-nearby`, `cat-banned`, **`size-50`** and `floor-2nd`

to be consistent with the following discussion: 

> The answer could be: The `park-nearby` contributed €30,000; `size-50` contributed €10,000; `floor-2nd` contributed €0; `cat-banned` contributed -€50,000.

**Comment by christophM** [comment]
thanks!
