### ISSUE TITLE
Write a chapter about your favorite tree ensemble interpretability method

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#16]
Tree ensembles like boosted trees (e.g. xgboost) and random forests perform extremely well on tabular data. 

A few interpretability methods are created to interpret specifically tree ensembles. 

Some pointers: 

- https://github.com/andosa/treeinterpreter
- https://github.com/lantanacamara/lightgbmExplainer
- https://github.com/AppliedDataSciencePartners/xgboostExplainer
- https://github.com/araastat/reprtree

Leave a comment if you are interested in writing a chapter about a tree ensemble-specific method!

**Comment by mstaniak** [comment]
Note: there is also [https://github.com/MI2DataLab/randomForestExplainer](randomForestExplainer)

**Comment by asstergi** [comment]
There are also the SHAP values which have been integrated into XGBoost and LightGBM packages as well and offer some theoretical advantages over LIME: https://github.com/slundberg/shap

**Comment by heaven00** [comment]
Also another python library https://github.com/TeamHG-Memex/eli5
