### ISSUE TITLE
Assumption on Linear Regression

### ISSUE THREAD

**Issue by chaupmcs** [christophM/interpretable-ml-book#161]
Hi Christoph,

Thank you for the great work on Explainable AI.
On the Linear Regression chapter, it states that 
["The outcome given the features might have a non-Gaussian distribution"](https://christophm.github.io/interpretable-ml-book/extend-lm.html#glm)
I think it should be _Normal distribution of error terms_, instead of _normal distribution of the outcome_.

Please let me know if I'm wrong about that.
Thanks and keep up the good work.
I am looking forward to the next chapters on Neural Network.

Best regards.

**Comment by christophM** [comment]
Thank you for your comment.

Both is correct.
The error terms have a normal distribution.
The outcome has a normal distribution as well, given the features.

It would be only incorrect to say that the outcome itself (without conditioning on the features) is normal distributed.
