### ISSUE TITLE
Wrong Formula: Adjusted R-square

### ISSUE THREAD

**Issue by MaximusWudy** [christophM/interpretable-ml-book#164]
Hi Christoph,

I really love  your book and am reading it! However I found a rather severe mistake in the Adjusted R-square formula in the book that might be very misleading to the readers. 

Link to wrong formula (**the formula is right above the "feature importance" section**): 
https://christophm.github.io/interpretable-ml-book/limo.html#interpretation
Right formula in Wiki: 
https://en.wikipedia.org/wiki/Coefficient_of_determination#Adjusted_R2

Thanks!

**Comment by christophM** [comment]
Good catch. Thanks a lot.
