### ISSUE TITLE
Question on feature importance

### ISSUE THREAD

**Issue by huanfachen** [christophM/interpretable-ml-book#166]
Can we say 'one feature is more important than another' after comparing the feature importance? For example, using the absolute value of the t-statistic in linear regression.
It sounds okay, but I would like to confirm this. Is there any literature on this?

**Comment by christophM** [comment]
Depends how you define "important". For permutation feature importance you can say that one feature causes more performance loss when permuted than another feature.
I don't think there is a single clear definition of what importance in the context of model interpretation is.
