### ISSUE TITLE
ALE for multi-label classification

### ISSUE THREAD

**Issue by jsanket9578** [christophM/interpretable-ml-book#167]
The examples discussed in the chapters do not include a multi-label classification. As per my understanding, if there are 'n' classes, there would be 'n' graphs for each feature of interest. Since the model chooses the class with the maximum probability in such cases, there can be large deviations for a given feature and a class (and therefore high ALE) even if this class was mostly non-dominant in the output. 
One potential way to solve this problem can be to only include samples where that class is actually the dominant class. Is there any other way to solve this problem?
Also, I think that PDPs should not suffer with this problem since they don't measure deviations.

Please confirm if my understanding is correct. Thanks.

**Comment by christophM** [comment]
You can create one ALE curve per predicted probability (and per feature). For this you need a model that outputs probabilities.
For PDP it is the same.

**Comment by jsanket9578** [comment]
> You can create one ALE curve per predicted probability (and per feature). For this you need a model that outputs probabilities.
> For PDP it is the same.

Thanks for confirming!
