### ISSUE TITLE
Possible mistakes in lime-text-explanations example.

### ISSUE THREAD

**Issue by MiaoDX** [christophM/interpretable-ml-book#17]
Hai, thanks for the efforts on the interpretation of ML methods. In [Ch5](https://github.com/christophM/interpretable-ml-book/blob/master/chapters/05.5-agnostic-lime.Rmd), the last example on lime-text-explanations, it seems that the generated image has both instance labeld as `spam`. At least in the [HTML version](https://christophm.github.io/interpretable-ml-book/lime.html). Some minor mistakes?

**Comment by christophM** [comment]
Thanks for catching that. 
I selected a better comment. 

But also the LIME output is a bit special: It always shows 'spam' together with the probability for it.
