### ISSUE TITLE
Comparing interpretation across different models

### ISSUE THREAD

**Issue by huanfachen** [christophM/interpretable-ml-book#180]
Hi Christoph,

Thanks for this great book. 

Is there any systematic approach to compare the interpretation of different models? For example, I have built a linear regression model and a random forest model for a classification problem, and then computed permutation importance for each feature per model. Can I compare the strength or ranking of the importance score in the two models?

**Comment by christophM** [comment]
A bit late, but the answer is that the most simple thing is to compare rankings.
Feature importance based on the loss is more difficult, as the models might have very different performances. But if you use the ratio to compare the PFI, this can be mitigated  a bit.
