### ISSUE TITLE
Add example to paragraph 4.1.6

### ISSUE THREAD

**Issue by FrieseWoudloper** [christophM/interpretable-ml-book#185]
> If all numerical features are mean centered (feature minus mean of feature) and all categorical features are effect coded, the reference instance is the data point where all the features take on the mean feature value. 

Could you please illustrate this by extending the bikes example in the previous paragraph?

**Comment by christophM** [comment]
Thanks for raising this issue. I am not planning to go deeper into the rabbit hole of encodings for categorical variables, and rather leave that to literature for regression modeling.
