### ISSUE TITLE
Chapter 4, Section 4.2.1: Figure 4.5's caption makes no sense.

### ISSUE THREAD

**Issue by gialmisi** [christophM/interpretable-ml-book#192]
First of all, I really appreciate this book. I am opening this issue, because I want this book to become a great book! My problem is with the content mentioned in the subject of this issue:

From the caption: `For the data on the left, we can use 0.5 as classification threshold.` Yet, in the figure it says the threshold on the left is *not ok*. The caption also says: `After introducing a few more malignant tumor cases, the regression line shifts and a threshold of 0.5 no longer separates the classes.` Again, the data on the left seems to have more malignant tumor cases than the data on the right. I would expect to see the progress resulting from adding data to go from the left to the right, but it seems it is from the right to the left. Not to mention the non-nonsensical remark about the threshold in the caption text.

Please correct me if I have interpreted this wrong. I did not make an attempt to fix this myself yet, because it might also be just the case of me not understanding the figure correctly.

**Comment by christophM** [comment]
your suggestion is correct. the order does not match

**Comment by christophM** [comment]
thanks for finding and reporting this!
