### ISSUE TITLE
Wrong links in navigation sidebar

### ISSUE THREAD

**Issue by johannesjung** [christophM/interpretable-ml-book#196]
E.g. the subsection _Advantages_ of [5.3 Accumulated Local Effects (ALE) Plot](https://christophm.github.io/interpretable-ml-book/ale.html) links to [Linear Regression's Advantages (4.1.8)](https://christophm.github.io/interpretable-ml-book/limo.html#advantages), as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/24568449/88153994-79968880-cc06-11ea-9ba7-414f62b6427f.png)

I haven't worked with bookdown / gitbook before, but I suspect that creating unique identifiers based on headings somehow fails. And then always the first occurrence of a subsection heading is linked.

**Comment by christophM** [comment]
Good catch, thanks. Seems more like an issue with bookdown. I have not encountered this problem before, so maybe this is a newly introduced issue.
