### ISSUE TITLE
Shapley value estimation steps, instance example

### ISSUE THREAD

**Issue by lucyleeow** [christophM/interpretable-ml-book#199]
In section '5.9.3.3 Estimating the Shapley Value':

https://github.com/christophM/interpretable-ml-book/blob/4759479f5d4287eaf353ab9db6cbeee506e54046/manuscript/05.9-agnostic-shapley.Rmd#L320-L321

should the 'x' and 'z' be reversed, to match with the words below:
> The first instance x+j is the instance of interest, but all values in the order before and including value of feature j are replaced by feature values from the sample z.

(the paper "Explaining prediction models and individual predictions with feature contributions" seems to match the above sentence.)

e.g.:
With feature j: x+j=(z(1),…,z(j−1),x(j),x(j+1),…,x(p))

**Comment by christophM** [comment]
Good catch! Thanks a lot.

**Comment by christophM** [comment]
The order of x and z is correct and matches with the paper.
But x_{+j} and x_{-j} where wrongly explained below the algorithm.

**Comment by lucyleeow** [comment]
Thanks for looking into this @christophM!

Sorry, I am probably confused about this, maybe you can clarify for me. From:
> but all values in the order before feature j are replaced by feature values from the sample z

I would have thought that for either instance (`$x_{+j}$` and `$x_{-j}$`), the first values would be values from sample z, and the values after `j` index would be from sample x, so for `$x_{+j}$` it would look like:
```
x+j = ( z(1), z(2)....z(j-1), x(j), x(j+1)....x(p) )
```
