### ISSUE TITLE
Create better pictograms for explaining the Shapley value

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#20]
They are hand drawn and I am not super happy with them. 
 Help to improve those is appreciated. 

The location in the book: https://github.com/christophM/interpretable-ml-book/blob/master/chapters/05.6-agnostic-shapley.Rmd

![shapley-coalitions](https://user-images.githubusercontent.com/1632100/36167746-3535a63e-10f7-11e8-8d16-36b90a0593d4.png)
![shapley-instance-intervention](https://user-images.githubusercontent.com/1632100/36167747-35556eb0-10f7-11e8-84ed-7e9315051e72.png)
![shapley-instance](https://user-images.githubusercontent.com/1632100/36167748-3571fa76-10f7-11e8-89b5-6c067932b326.png)

**Comment by abi-aryan** [comment]
Can I email you these?

**Comment by christophM** [comment]
Thanks!

You can attach them here by pulling them into a comment. Or you can send them to christoph.molnar.ai@gmail.com

**Comment by abi-aryan** [comment]
Sent. Check email. 

![screen shot 2018-05-06 at 20 47 25](https://user-images.githubusercontent.com/7281944/39684418-ab4df1c8-5170-11e8-870d-79a42752b5c7.png)

**Comment by abi-aryan** [comment]
Can we close this now?

**Comment by christophM** [comment]
Integrated now!
Looks so much nicer now: https://christophm.github.io/interpretable-ml-book/shapley.html

Thanks @abi-aryan !
