### ISSUE TITLE
Add citation for "TreeSHAP can produce unintuitive feature attributions."

### ISSUE THREAD

**Issue by sethah** [christophM/interpretable-ml-book#213]
The paragraph on "TreeSHAP can produce unintuitive feature attributions." is helpful but it seems to lack an explanation/clarity on why this happens. I *think* this might be in reference to https://arxiv.org/abs/1910.13413 and there's some discussion of it [here](https://github.com/slundberg/shap/issues/882) as well. If so, I thought it might be useful to include a reference.

Thanks for this incredible book!

**Comment by sethah** [comment]
Ok, I just now am seeing that you already have a reference to it in another section in the same chapter. In that case, I suppose my only suggestion is to link it also in the paragraph I mentioned because I somehow missed it all this time. Feel free to ignore if you think it's sufficient as is!

**Comment by christophM** [comment]
Thanks for bringing up that point. I will close the issue, as I don't plan to go deeper in this topic.
