### ISSUE TITLE
How to interpret the ALE plot?

### ISSUE THREAD

**Issue by xiaochi-liu** [christophM/interpretable-ml-book#221]
Hello @christophM, 

Many thanks for this outstanding book. 

I have a small question about how to interpret the ALE plot. In section 5.3.3, you wrote:

![image](https://user-images.githubusercontent.com/48895627/101417545-fde07280-393f-11eb-9942-276596f2bf97.png)

So, what does the "average prediction" exactly mean? When I write the result section of a journal article, I think it's better to provide this average prediction. So how to calculate it?

Your kind guidance would be much appreciated!

**Comment by christophM** [comment]
The average prediction is when you take all of your data, get the prediction for it and average it

**Comment by xiaochi-liu** [comment]
Thank you very much @christophM. Can I get this average prediction using `iml`?
