### ISSUE TITLE
HTTP 410 error

### ISSUE THREAD

**Issue by zhi-liu-dev** [christophM/interpretable-ml-book#252]
the link of "This publication is under investigation or was found in violation of the Medium Rules" on Page 13 do not work. If you click it, it will jump to https://medium.com/kaggle-blog and show " This publication is under investigation or was found in violation of the Medium Rules".

**Comment by christophM** [comment]
which link?

**Comment by zhi-liu-dev** [comment]
Sorry for the confusion. The hyperlink of the sentence "interviews with winners on the kaggle.com machine learning competition platform" in section 1.2 "**What Is Machine Learning?**". It shows "410  This publication is under investigation or was found in violation of the Medium Rules" if clicking it.

**Comment by christophM** [comment]
Thanks!
