### ISSUE TITLE
get_effects() should have gsub() edits applied to reference_X and not just X

### ISSUE THREAD

**Issue by brshallo** [christophM/interpretable-ml-book#262]
Tried running these functions on another dataset and got an error:

```r
mod <- lm(Sepal.Length ~ ., data = iris)
iml.book::get_effects(mod, iris)
#> Error in reference_X[1, names(X)] : subscript out of bounds
```

This occurs because in `get_effects()` the changes to `colnames()` from `gsub()` are applied only to `X` but are not applied to the names for `reference_X` so get subscript error during `apply()` step if had non-characters in column names.

# Sidenote

Would love if some of these funs were put into a separate package (or if have tips on other established packages for effect plots).

**Comment by christophM** [comment]
Hi Bryan. I am not planning to put this into a separate package or anything, I am happy as long as the code works for the examples in the book.

**Comment by brshallo** [comment]
It might be helpful to add a "software" section for 4.1. providing recommendations on available packages.
