### ISSUE TITLE
Found introduction on splines in 5.3. confusing 

### ISSUE THREAD

**Issue by brshallo** [christophM/interpretable-ml-book#312]
(Caveat that this may be my own misunderstanding or just me having trouble connecting related explanations between what's in IML with the way the topic is introduced in ISLR.)

I found your introduction on splines in 5.3 a bit confusing to my general understanding of splines, specifically:

> Splines are functions that can be combined in order to approximate arbitrary functions. A bit like stacking Lego bricks to build something more complex...

My understanding is that this description applies more to *basis functions* which are ultimately used to build splines (typically). So it's more that *basis functions are stacked to build smoothed splines* -- and that the intuition for splines is more about fitting non-linear models that can have different characteristics in different regions (which is why they are usually introduced after polynomial piecewise regression).

I don't know if there may be another way of introducing splines here in a way that gets across the typical intuition provided on splines (e.g. regarding knots) but that also sets-up the basis functions used to build them and that therefore segways nicely with GAMs...

**Comment by christophM** [comment]
How did I miss this ...
You are absolutely right, I muddled together the splines and spline basis functions.
Thanks for pointing it out, I tried to make the distinctions clearer.
