### ISSUE TITLE
Naive Bayes is a linear model

### ISSUE THREAD

**Issue by JEHoctor** [christophM/interpretable-ml-book#314]
In the summary table in the intro to chapter 5, Naive Bayes is marked as a non-linear model. From my superficial research his seems to be false in some important cases, though it may be true in some others. Here are some reference materials collected via search engine:

- https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Multinomial_na%C3%AFve_Bayes
- https://people.csail.mit.edu/jrennie/papers/icml03-nb.pdf
- https://stats.stackexchange.com/questions/142215/how-is-naive-bayes-a-linear-classifier
- https://www.cs.cornell.edu/courses/cs4780/2018fa/lectures/lecturenote05.html
- https://svivek.com/teaching/lectures/slides/naive-bayes/naive-bayes-linear.pdf

The most basic argument here is that Naive Bayes takes a product of probabilities, and this can be converted to a sum using a logarithm. Does this mean that Naive Bayes is compatible with explanation techniques for linear models? Does the logarithm interfere with this?

**Comment by christophM** [comment]
That's correct. The same is true for logistic regression. I added two sentences to clarify this to the table. Thanks for raising this!
