### ISSUE TITLE
gs in the optimiser does not appear in the function in chapter "Generalized Functional ANOVA for Dependent Features"

### ISSUE THREAD

**Issue by ec0github** [christophM/interpretable-ml-book#315]
The function gs in the optimiser does not appear in the function

<img width="547" alt="Screenshot 2022-02-05 at 13 50 41" src="https://user-images.githubusercontent.com/10429223/152630471-c0c1e727-bc3f-448d-9358-b005efe6a5b9.png">

I guess it should be
<img width="576" alt="Screenshot 2022-02-05 at 14 01 31" src="https://user-images.githubusercontent.com/10429223/152630689-557130a1-4370-42d7-ac19-693509231001.png">

Am I right?

**Comment by christophM** [comment]
you are absolutely right, thanks for reporting!
