### ISSUE TITLE
An Equation in Section 9.6.5 SHAP Feature Importance

### ISSUE THREAD

**Issue by laugoon** [christophM/interpretable-ml-book#318]
Dear sir,

The book Interpretable Machine Learning is really interesting!
But I'm confused about an equation in Section 9.6.5 SHAP Feature Importance:
![image](https://user-images.githubusercontent.com/37583259/156681274-ae7b4e44-17a8-49cc-a63c-0e92fa15a314.png)
As written in the book: 'average the absolute Shapley values per feature across the data', 
I think the ϕ_j^i is the feature attribution for a feature j, instance i, the Shapley value.
And the I_j is the feature importance value of feature j.
So why doesn't the equation look like this:
![image](https://user-images.githubusercontent.com/37583259/156681300-5d05baa6-ea7b-4602-9ada-06a69dee11f1.png)
Please correct me if I am wrong, and forgive my poor English.
Thanks for your reading, I'm looking forward to hearing from you.
Lagoon

**Comment by christophM** [comment]
Yes, that's a mistake. Thanks for notifying me! It's fixed now.
