### ISSUE TITLE
Broken link to paperback

### ISSUE THREAD

**Issue by fritzel56** [christophM/interpretable-ml-book#338]
Loving book. Wanted to buy a hard copy as I like to write in books as I go.

The `Buy Book` link takes you to [leanpub](https://leanpub.com/interpretable-machine-learning). On the leanpub page it says `The print version can be bought here: http://bit.ly/iml-paperback`. This link takes you to a `404 Page Not Found` page. I did eventually realize I could buy it on Amazon but would be great to update this link to prevent others getting lost.

**Comment by christophM** [comment]
Thanks a lot! It's updated now
