### ISSUE TITLE
How to interprete Accumulated Local Effects plot

### ISSUE THREAD

**Issue by xiaochi-liu** [christophM/interpretable-ml-book#360]
Hello, I'm reading Chapter 8.2 "Accumulated Local Effects (ALE) Plot". May I ask how to interpret the Accumulated Local Effects (ALE) Plot?

In Section 8.2.3 "Estimation", it says:

> The value of the ALE can be interpreted as the main effect of the feature at a certain value compared to the average prediction of the data. For example, an ALE estimate of -2 at $x_j=3$ means that when the j-th feature has value 3, then the prediction is lower by 2 compared to the average prediction.

However, in [another book talking about ALE](https://ema.drwhy.ai/accumulatedLocalProfiles.html#fig:featureEffectsApartment), the interpretation is different, and they can even draw partial dependence and accumulated local effect in the same plot, such as [Figure 18.5](https://ema.drwhy.ai/accumulatedLocalProfiles.html#fig:featureEffectsApartment).

I was wondering, is there something different in the theory?

Your kind guidance is much appreciated!

**Comment by christophM** [comment]
You can plot both curves in the same plot when you add the mean prediction to the ALE curve.
Often they also will look similar.

**Comment by xiaochi-liu** [comment]
Thank you very much for your guidance @christophM! Crystal clear.
