### ISSUE TITLE
TCAV sensitivity sign issue

### ISSUE THREAD

**Issue by mlai-po** [christophM/interpretable-ml-book#395]
are the signs correct in this line

If the angle is greater than 90 degrees,  
S
C
,
k
,
l
(
x
)
  will be positive, and if the angle is less than 90 degrees,  
S
C
,
k
,
l
(
x
)
  will be negative. 

on this page https://christophm.github.io/interpretable-ml-book/detecting-concepts.html

it seems to me sensitivity should be positive when the angle is smaller than 90 degrees and maximal at angle zero

**Comment by fangzhouli** [comment]
Hi, thank you for your keen eyes! You are completely right. I have issued a pull request.

Best,
Fang

**Comment by christophM** [comment]
Thanks, both of you!
