### ISSUE TITLE
 List  alternatives and software for partial dependence plots 

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#50]
I am extending all chapters with a section for software implementations and to alternative algorithms (also with software implementation). The software can be any free and open source software: R, Python, Weka, ...

You can help out by posting links to alternatives and software implementations of partial dependence plots  algorithms as comments to this issue.

**Comment by christophM** [comment]
condvis 
https://cran.r-project.org/web/packages/condvis/index.html 
https://arxiv.org/abs/1610.00290

**Comment by see24** [comment]
pdp
[https://CRAN.R-project.org/package=pdp](https://CRAN.R-project.org/package=pdp)
ICEbox
[ https://CRAN.R-project.org/package=ICEbox]( https://CRAN.R-project.org/package=ICEbox)
