### ISSUE TITLE
 List alternatives and software for feature importance measures

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#52]
I am extending all chapters with a section for software implementations and to alternative algorithms (also with software implementation). The software can be any free and open source software: R, Python, Weka, ...

You can help out by posting links to alternatives and software implementations of feature importances measure algorithms as comments to this issue.

**Comment by christophM** [comment]
PIMP for testing feature importance and correcting biases
package: https://www.rdocumentation.org/packages/vita/versions/1.0.0/topics/PIMP
paper: Permutation importance: a corrected feature importance measure

**Comment by philip-khor** [comment]
Looks like permutation importances is already implemented in R's randomForest. From this article (http://explained.ai/rf-importance/index.html):

> For R, use importance=T in the Random Forest constructor then type=1 in R's importance() function. 

Also, for Python, 
> To get reliable results in Python, use permutation importance, provided here and in our rfpimp package (via pip). 
https://github.com/parrt/random-forest-importances
