### ISSUE TITLE
 List shapley value alternatives and software 

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#55]
I am extending all chapters with a section for software  implementations and to alternative algorithms (also with software  implementation). The software can be any free and open source software:  R, Python, Weka, ... 

You can help out by posting links to papers and software  implementations of the shapley value for machine learning as comments to this issue.

**Comment by expectopatronum** [comment]
Python package by S. Lundberg: [shap](https://github.com/slundberg/shap)
[S. Lundberg, A unified approach to Interpreting Model Predictions](https://arxiv.org/abs/1705.07874)
[S. Lundberg, Consistent Individualized Feature Attribution for Tree Ensembles](https://arxiv.org/abs/1802.03888)
[S. Lundberg, Consistent feature attribution for tree ensembles](https://arxiv.org/abs/1706.06060)
