### ISSUE TITLE
Confusing difference for Figure 5.22

### ISSUE THREAD

**Issue by expectopatronum** [christophM/interpretable-ml-book#56]
I guess it's because of rounding but at first I was a bit confused that the "difference" between the actual prediction (0.43) and the average prediction (0.03) is 0.41. I think it might confuse readers and could be explained in the text. If you agree I can add a sentence to explain it.
![image](https://user-images.githubusercontent.com/2265475/40698604-19beffd2-63d0-11e8-884c-3138c20dcd62.png)

**Comment by christophM** [comment]
That is weird. It's a mistake in the iml package. I opened an issue there:

https://github.com/christophM/iml/issues/19
