### ISSUE TITLE
Figure text for figure 5.10 and 5.11 is the same.

### ISSUE THREAD

**Issue by rasorensen90** [christophM/interpretable-ml-book#57]
I guess this text is for figure 5.10 and not figure 5.11?

FIGURE 5.11: The interaction strength for each feature with all other features for a random forest predicting the probability of cervical cancer. The number of diagnosed sexually transmitted diseases has the highest interaction effect with all other features, followed by the number of pregnancies.

**Comment by christophM** [comment]
Thanks for spotting. 
This is fixed now.
