### ISSUE TITLE
Error in the RuleFit -> Guidelines -> Disadvantages

### ISSUE THREAD

**Issue by So-Cool** [christophM/interpretable-ml-book#64]
In the **Disadvantages** section of the RuleFit [Guidelines](https://christophm.github.io/interpretable-ml-book/rulefit.html#guidelines) you write:

"*For example one decision rule (feature) for the bike prediction could be: “temp > 15” and another rule could be “temp > 10 & weather=‘GOOD’”. When the weather is good and the temperature is above 10 degrees, the temperature is automatically also always bigger then 15, which means in the cases where the second rule applies, the first one also always applies.*"

I think that you have swapped the numbers around and the rules should be:
* temp > 10, and
* temp > 15 & weather=‘GOOD’.

`temp > 10 & weather=‘GOOD’` does not imply `temp > 15`, e.g. `weather=‘GOOD’ & temp = 13`.

**Comment by christophM** [comment]
Good catch, thank you!
