### ISSUE TITLE
Add GAMs to chapter Interpretable Models

### ISSUE THREAD

**Issue by noleto** [christophM/interpretable-ml-book#73]
Hi Christoph, 

First of all a big bravo and thank you for writing such an interesting book and making it open to everyone!

I would suggest adding a section on generalized additive models, although not very popular in the data science community, these methods are very powerful and simple for balancing accuracy vs. interpretability. 

You probably saw the Caruana talks abou GAMS for HealthCare, in any case here goes the link: https://www.microsoft.com/en-us/research/video/intelligible-machine-learning-models-for-healthcare/

Cheers,

**Comment by christophM** [comment]
Yes, good point. 
I started working on a chapter about extending linear models.

The chapter will cover:

- What to do when y is not normal -> GLM
- What to do when the relation between x_j and y is not linear -> feature transformations, GAMs (splines)
- What to do when there are interactions between features -> manual integration of interaction effects, automatic detection
- What to do when the data is not i.i.d. -> mixed models, GEEs (not going to deep into this topic)

What is missing?

**Comment by christophM** [comment]
https://github.com/christophM/interpretable-ml-book/tree/extend-lm
