### ISSUE TITLE
Friedman’s H-statistic formula

### ISSUE THREAD

**Issue by Macuyiko** [christophM/interpretable-ml-book#78]
In https://christophm.github.io/interpretable-ml-book/interaction.html#theory-friedmans-h-statistic

The two formula's under

> In mathematical terms, the H-statistic for the interaction between feature [...] proposed by Friedman and Popescu is:

Should have a ^2 (i.e. be squared) added around the square brackets in de numerator as well, when comparing to the [paper](https://arxiv.org/pdf/0811.1679.pdf), I believe.

**Comment by christophM** [comment]
Thanks. I fixed it.
