### ISSUE TITLE
Gitbook

### ISSUE THREAD

**Issue by snowde** [christophM/interpretable-ml-book#80]
Gitbook seems to now only have a legacy option. Did you use the editor to create this on your desktop ? Can you possibly recommend an easy way to get gitbook going. I love your work and have linked to it via one of my websites.

**Comment by christophM** [comment]
I used the bookdown package in R. And the guy book option. The description is on the Readme. 
could you share the link to your website ?

**Comment by snowde** [comment]
With this book writing strategy, I guess it is not too hard to use python as opposed to R. If you don't recommend rmd for that, would you have any other suggestions.
