### ISSUE TITLE
Need more clarity on 5.1.5.

### ISSUE THREAD

**Issue by pedroallenrevez** [christophM/interpretable-ml-book#82]
<img width="788" alt="screen shot 2018-11-02 at 17 47 54" src="https://user-images.githubusercontent.com/15174747/47931698-7eae2400-dec7-11e8-9923-4a505155d441.png">

I think this paragraph needs more clarity when explaining how the effects on each feature (for this instance) affect the prediction.

Most of the confusion come from expressions like "unusually little or much".

First and foremost, providing the used instance allows the reader to have a little bit more context.

More concepts that are not clear:
1. Is "Temperature (2 degrees)" the data from this instance, or meaning that two unit increases?
2. "contributes less towards the predicted value compared to the average" - what is the average? Average predictions? Mean value of distribution?
3. "“days_since_2011” unusually much, because this instance is from late 2011 (5 days)." - so the features contributes a lot because it is from late 2011 (only 5 days????). Shouldn't it be 300 days or so?

Thanks a lot for the book, it is very well written, but I do feel that this example needs a little bit more of step-by-step explanation.
e.g.: Providing the instance, showing how it maps to the plot (calculating effects), and cross-referencing to the weight table, in order to have a full grasp of what is going on.

P.S.: It would also be really nice to have the data with the extracted features in order to reproduce the work.

**Comment by christophM** [comment]
Thank you for the feedback. I agree, this section needed improvements.
Do you think it is good now?

**Comment by pedroallenrevez** [comment]
Much clearer now, thank you.
You can't go wrong with a specific example!

**Comment by christophM** [comment]
You are right. Thanks again. Feedback like yours  helps me immensely to improve the book!

**Comment by pedroallenrevez** [comment]
I will be reading the whole book until the end of December, so I will definitely have more feedback.
I'm also thinking of doing an implementation in Python, so the two audiences could have material to mess around with. No guarantees tho! :)
