### ISSUE TITLE
Decision Trees Chapter

### ISSUE THREAD

**Issue by pedroallenrevez** [christophM/interpretable-ml-book#85]
On 4.4.2. on the example you talk about purity (of Gini index).
But you don't reference it anywhere else, which might add to the confusion of the reader.

I have some background so I know what you are talking about, but others will not!

So, either reference a link to Gini Index and what is this purity,
or just give the intuition that purity is relative to the subsets, and can be dirty if it has instances that do not "belong" to that group.

As always, keep up the good work,
Pedro

**Comment by christophM** [comment]
Thanks for the feedback.
I added a bit about the intuition of the Gini index.
