### ISSUE TITLE
Create a pretty version of tree-to-rules graphic

### ISSUE THREAD

**Issue by christophM** [christophM/interpretable-ml-book#9]
The graphic that shows how a tree can be turned into decision rules is currently drawn by hand. 
It would be great to have a pretty version of it, created on a computer. 
The format can be SVG (preferred), png or jpg. 
The filename is: rulefit.jpg
![rulefit](https://user-images.githubusercontent.com/1632100/34325646-e86cfa6e-e897-11e7-8050-87bc62f52f39.jpg)

**Comment by expectopatronum** [comment]
I created a first draft, what do you think of it? I can play around with the "roundness" of the arrows a little bit more.
![image](https://user-images.githubusercontent.com/2265475/38910847-c645895e-42cb-11e8-8670-818080b1ba23.png)

**Comment by christophM** [comment]
It looks really great!
I just noticed that my hand writing is not so great: The red annotations are supposed to be 'r' and not 'T'. When that is fixed it is ready to be integrated.

**Comment by expectopatronum** [comment]
or my eyes are bad :) how should I integrated it? a separate pull request?

![image](https://user-images.githubusercontent.com/2265475/38940583-c477ab84-432a-11e8-8b41-f3c1d0b04783.png)

**Comment by christophM** [comment]
You can also integrate it with the other PR.

**Comment by abi-aryan** [comment]
Let's close this too?

**Comment by christophM** [comment]
Integrated now
