### ISSUE TITLE
render_book error: Cannot open file '10-references.Rmd'

### ISSUE THREAD

**Issue by annacodes** [christophM/interpretable-ml-book#91]
I'm progressing through your README file and upon executing line 34:

`bookdown::render_book('', 'bookdown::gitbook')`

I receive the following error:

```Error` in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '10-references.Rmd': No such file or directory```

I checked the 'manuscript' folder for the following file: '10-references.Rmd' but did not see it in the folder.

Thank you for your time!

**Comment by christophM** [comment]
I create the file 10-references.Rmd with a script. I updated the README accordingly. Try out the new instructions.
