### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by fjug** [christophM/interpretable-ml-book#93]
Hi Christoph,

lovely, thanks a lot for the book.
I might sound semi-old asking for the possibility to build a PDF version of your book, but in order to read and make notes on e.g. an iPad or other tablet this would make a lot of sense to me.

Is there any way to do so?

**Comment by christophM** [comment]
You can find it here : leanpub.com/interpretable-machine-learning

Am Do., 17. Jan. 2019, 16:58 hat Florian Jug <notifications@github.com>
geschrieben:
