### ISSUE TITLE
explanation on how weights calculated in 5.7.2.1 Example

### ISSUE THREAD

**Issue by kfattila** [christophM/interpretable-ml-book#94]
Very good book, thanks for writing it! :)

Just one issue: would you please give us some explanation on how the weights were calculated in the 5.7.2.1 Example. (second table, last column, after the probs).  I understand it is a distance between the generated sample text and the original sentence. Could you please give us some hints on how the distance between sentence (or set of words) were calculated?

Sorry, this issue is addressed somewhere.

**Comment by christophM** [comment]
Good point, I added a sentence to explain it.
