### ISSUE TITLE
Significance of gbm interactions

### ISSUE THREAD

**Issue by see24** [christophM/interpretable-ml-book#95]
In section 5.4.5 you say:
"It is unclear whether an interaction is significantly greater than 0. We would need to conduct a statistical test, but this test is not (yet) available in a model-agnostic version."
I know that Friedman and Propescu 2008 recommend a method to create a null distribution in order to determine the significance of interactions for a gbm model. Do you know if this method is implemented in R anywhere, even if just for gbm models?

**Comment by christophM** [comment]
As mentioned it's available for `gbm` and `pre` (RuleFit) and I don't know of any more implementations
